### ISSUE TITLE
Feature Request: Add project-based filtering in VM Registry Component

### ISSUE THREAD

**Issue by raserma** [sysdiglabs/backstage-plugin-sysdig#11]
## Description
We would like to add a new filter within the VM registry component that allows filtering by project. Currently, the component returns the entire list of images in the registry. This enhancement will help narrow down the results by project.

An example URI that works on our side:
```ruby
https://$SYSDIG_SECURE_URL/secure/#/vulnerabilities/registry/
?filter=registry.vendor+%3D+%22$SYSDIG_REGISTRY_VENDOR_ANNOTATION%22
+and+registry.name+%3D+%22$SYSDIG_REGISTRY_NAME_ANNOTATION%22
+and+repository.name+%3D%22$SYSDIG_PROJECT_ANNOTATION%22
```

## Expected Results
Here is a screenshot of the expected results on the Sysdig UI side:
![Screenshot 2024-06-19 at 17 02 39](https://github.com/sysdiglabs/backstage-plugin-sysdig/assets/3873965/2f938007-3858-4dec-a92f-4bb028fdb494)

## Rationale
This feature is needed to reduce noise for developers by notifying them only of the projects they are working on. Without this filter, developers receive notifications for all projects, which can be overwhelming and counterproductive.

## Implementation notes

I'm not familiar with Typescript but if I understand correctly, we could add a new filter [here](https://github.com/sysdiglabs/backstage-plugin-sysdig/blob/main/src/components/SysdigVMRegistryFetchComponent/SysdigVMRegistryFetchComponent.tsx#L123-L131). So it would be a matter of importing the SYSDIG_PROJECT_ANNOTATION (or any other) and using them in the new filter generation. 

Is this approach feasible? Any guidance on how to implement this would be greatly appreciated.

Thank you!

EDIT: Updated the example URI variables

**Comment by Jujuyeh** [comment]
You are 100% right. Just tested that filter, so I think it just makes sense to add a new annotation supporting it. Let me come back with the addition. Thank you for the detailed explanation, it was very helpful!

**Comment by Jujuyeh** [comment]
Just dropped a new release. Let's see if that helps. 😄 

https://github.com/sysdiglabs/backstage-plugin-sysdig/releases/tag/1.3.0

Will close the issue for now - Feel free to re-open if you still have any concerns with these changes. Thank you!
