### ISSUE TITLE
The new backlink visibility issue 

### ISSUE THREAD

**Issue by AhmedRaafat14** [sysdiglabs/backstage-plugin-sysdig#14]
Hi!
Thanks for your continues improvements to this plugin.

I have upgraded to the latest version and hit an error that I must set a value to the new `backlink` field, even though the readme file mentions it is optional:
```md
+   backlink: https://... # Optional override base link for backlinks. It must end in '/'.
```

So, I think it needs to be updated in the `config.d.ts` to be with the `?` to not make it `required`!

```ts
/**
       * Custom backlink to Sysdig Secure.
       * @visibility frontend
       */
      backlink?: string;
    };
```

Thanks

**Comment by Jujuyeh** [comment]
Absolutely right! Thank you very much for the suggestion! 😄 

Closing issue as solved by #15 . Please, re-open if the issue persists.
